[package]
name = "rusty-clock"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30"
winit = "=0.30.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[workspace]
resolver = "2"