name: Build and Release RustyClock binary

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Rust Toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      # Build release
      - name: Build release
        working-directory: ./rusty-clock
        run: cargo build --release

      # Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/rusty-clock
          generate_release_notes: true
          tag_name: ${{ github.run_number}}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
