name: Build and Release RustyClock binary

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      #1. checkout repo
      - uses: actions/checkout@v3

      #2. Install Rust
      - uses: actions-rs/toolchain@v3
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Build release
        run: cargo build --release
      
      - name: Create Github Release
          id: create_release
          uses: softprops/action-gh-release@v1


