name: Build and Release RustyClock binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Build release
        working-directory: ./rusty-clock
        run: cargo build --release

      - name: Create Github Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload binary
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/rusty-clock
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
