name: Build and Release RustyClock binary

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: macos-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Rust Toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Get short commit hash
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          TAG="v1.0.0-${SHORT_SHA}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # Build release
      - name: Build release
        run: cargo build --release

      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # Upload binary
      - name: Upload binary
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/rusty-clock
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
